### ISSUE TITLE
Move regression test code back to main repo

### ISSUE THREAD

**Issue by langner** [cclib/cclib-data#72]
See #71 for an example of complications that would be avoided. It feels like it will be more valuable to have fixes and test together than tests and data.

**Comment by langner** [comment]
Link to thread on cclib-devel: https://sourceforge.net/p/cclib/mailman/message/35996152/

**Comment by ATenderholt** [comment]
Yes, I agree. Will you have this done soon so we can get the other PRs, especially the fixes to ORCA linear frequencies in before 1.5.2?

**Comment by langner** [comment]
> Yes, I agree. Will you have this done soon so we can get the other PRs, especially the fixes to ORCA linear frequencies in before 1.5.2?

No, let's focus on the GSOC stuff for v1.5.2 and get it out as soon as possible. We can follow up with the next release as soon as we like.

**Comment by berquist** [comment]
What are we going to do about all the outstanding PRs in this repository?

**Comment by langner** [comment]
We have two options:
1) Do this now and deal with outstanding PRs.
2) Wait until all outstanding PRs are merged in (and don't allow new ones?).

I'd prefer the first.

**Comment by langner** [comment]
So I guess we're done with this. IMO it's better than before, having the code in the main repo alongside the parsers. It'd be great to get rid of `regressionfiles.txt` as well (or at least move it to the main repo also), and do the checks in facilitates in some other way. Then this repo would be just be a container of regression logfiles.
